### ISSUE TITLE
No game shows up in chovy-trans

### ISSUE THREAD

**Issue by BeemerDream** [LiEnby/chovy-trans#1]
Hi and thanks for your hard work!

I have a problem, i've downloaded my game from the US store (my main account is EU) to my PS3 and transfered it to the PSP.
But it won't show up in the PSP folder in chovy-trans.

**Comment by LiEnby** [comment]
It only shows up if it can find in /PSP/GAME and /PSP/LICENSE- it won't work on vita anyway unless it's also logged into ur US account

**Comment by LiEnby** [comment]
Oh also did you open Chovy-Trans before opening USB on your psp ? or after ? because it wont update until you select the correct drive letter also-

**Comment by BeemerDream** [comment]
Ok, thanks for your help.

Den tors 24 okt. 2019 23:23Bluzume <notifications@github.com> skrev:

**Comment by LiEnby** [comment]
please try with V1.1

**Comment by BeemerDream** [comment]
Ok, i will try it

Den tors 7 nov. 2019 14:40Bluzume <notifications@github.com> skrev:
