### ISSUE TITLE
Downloaded the File but dont know how to use it

### ISSUE THREAD

**Issue by talha007** [LiEnby/chovy-trans#3]
I have bought alot of games on the PSN store and would love to transfer my Crash Bandicoot to my ps vita how do I use this tool?

**Comment by LiEnby** [comment]
see https://github.com/KuromeSan/chovy-trans/commit/736cc8d831150cfc3907995ae9569055761e00ee

**Comment by talha007** [comment]
Perfect thank you! But now running into a problem, trying to transfer Twisted Metal Head On but it keeps saying the file is corrupt? Downloaded the game off PSN?

**Comment by LiEnby** [comment]
yes there are a few games that dont work properly. its probably why they disabled them from being transfered xD

**Comment by talha007** [comment]
Is there any way to transfer PS1 games that are not on the PSN store?

**Comment by LiEnby** [comment]
not yet, possibly with the psp signing keys .

**Comment by talha007** [comment]
Hopefully get to see that soon I just wanted to add one more game to my list Crash Bash so I can run 4 player multiplayer on the PS TV, appreciate your help!
